version: "3.9"
services:
  fl-client:
    build: ./client
    ports:
      - "8002:8002"
    # healthcheck:
      # test: ["CMD-SHELL", "curl --silent --fail localhost:8003/_cluster/health || exit 1"]
      # interval: 10s
      # timeout: 10s
      # retries: 3
    environment:
      - TZ=Asia/Seoul
      - DOCKER_DIST=1
      - MONITORING=1
    networks:
      - fedops
    volumes:
      - fedops-vol:/app/fedops
  client-manager:
    build: ./client_manager
    ports:
      - "8003:8003"
    environment:
      - TZ=Asia/Seoul
      - DOCKER_DIST=1
      - MONITORING=1
    networks:
      - fedops
    volumes:
      - fedops-vol:/app/fedops
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic
  
  logstash:
    image: logstash:7.17.3
    container_name: log
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config
      - fedops-vol:/home/fedops
    ports:
      - "5001:5000/tcp"
      - "5001:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: logstash -f /usr/share/logstash/pipeline/logstash-nginx.config
  kibana:
    image: kibana:7.17.3
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
networks:
  fedops:
    driver: bridge
  elastic:
    driver: bridge
volumes:
  fedops-vol: